spring:
  datasource:
    password: ${POSTGRES_PASSWORD}
    url: ${DB_URL}
    username: ${POSTGRES_USER}
  jpa:
    hibernate:
      ddl-auto: update # Or "create-drop"
    show-sql: true
# flyway:
#   url: ${DB_URL}
#   schemas: USERSERVICE
#   user: ${POSTGRES_USER}
#   password: ${POSTGRES_PASSWORD}
